import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {handle,validateRuntimeConfig} from '../src/worker.mjs';
import {D1Store} from '../src/storage.mjs';
import {applyCatalogManifest} from '../src/catalog_d1.mjs';
import {passwordVerifier,verifySession} from '../src/crypto.mjs';
import {proxyDriveMedia} from '../src/drive.mjs';

class Stmt{
  constructor(s,sql,params=[]){this.s=s;this.sql=sql;this.params=params}
  bind(...p){return new Stmt(this.s,this.sql,p)}
  all(){return {results:this.s.prepare(this.sql).all(...this.params)}}
  first(){return this.s.prepare(this.sql).get(...this.params)||null}
  run(){return this.s.prepare(this.sql).run(...this.params)}
}
class D1Mock{
  constructor(){
    this.s=new DatabaseSync(':memory:');
    this.s.exec(fs.readFileSync(new URL('../migrations/0001_init.sql',import.meta.url),'utf8'));
    this.s.exec(fs.readFileSync(new URL('../migrations/0002_integrity.sql',import.meta.url),'utf8'));
  }
  prepare(sql){return new Stmt(this.s,sql)}
  async batch(stmts){this.s.exec('BEGIN');try{const out=[];for(const st of stmts)out.push(await st.run());this.s.exec('COMMIT');return out}catch(e){this.s.exec('ROLLBACK');throw e}}
}
const AUTH_SECRET='a'.repeat(48),MEDIA_SIGNING_SECRET='m'.repeat(48),PASSWORD_PEPPER='p'.repeat(48);
const fakeServiceAccount=JSON.stringify({client_email:'lume-test@example.iam.gserviceaccount.com',private_key:'-----BEGIN PRIVATE KEY-----\nAA==\n-----END PRIVATE KEY-----\n'});
function env(DB){return {DB,AUTH_SECRET,MEDIA_SIGNING_SECRET,PASSWORD_PEPPER,GOOGLE_SERVICE_ACCOUNT_JSON:fakeServiceAccount,LUME_ENV:'production',LOGIN_RATE_LIMITER:{async limit(){return {success:true}}}}}
function req(path,init={}){return new Request(`https://lume.example${path}`,init)}
async function authHeader(DB,username,password){const r=await handle(req('/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})}),env(DB));assert.equal(r.status,200);const j=await r.json();return {authorization:`Bearer ${j.token}`,session:j}}
async function seed(DB){
  await applyCatalogManifest(DB,{revision:1,full:true,works:[{id:'w1',canonicalTitle:'SOLANIN',displayTitle:'Solanin',type:'manga',sections:['Grandes Clássicos'],editorialSections:['Recomendações'],tags:['drama'],sourceFolderIds:['folder1'],editions:[{id:'e1',language:'pt-BR',format:'pdf',volumeNumber:1,sourceFileId:'drive-file-1',fileName:'Solanin.pdf',byteSize:123,sha256:'abc'}]}],tombstones:[]});
  const now=new Date().toISOString();
  const users=[['a1','aluno','senha-aleatoria-aluno-123456','consumer','p1'],['a2','admin','senha-aleatoria-admin-123456','admin','pa']];
  for(const [id,username,password,role,profile] of users){
    const verifier=await passwordVerifier(PASSWORD_PEPPER,password);
    DB.s.prepare('INSERT INTO profiles(id,account_id,name,created_at,updated_at) VALUES(?,?,?,?,?)').run(profile,id,username,now,now);
    DB.s.prepare('INSERT INTO accounts(id,username,password_verifier,role,profile_id,disabled,created_at,updated_at) VALUES(?,?,?,?,?,0,?,?)').run(id,username,verifier,role,profile,now,now);
  }
}

test('production config fails closed without bindings/secrets',()=>{const v=validateRuntimeConfig({LUME_ENV:'production'});assert.equal(v.ok,false);assert.ok(v.issues.length>=5)});
test('health and readiness match current Flutter contract',async()=>{const DB=new D1Mock();await seed(DB);let r=await handle(req('/v1/health'),env(DB));assert.equal(r.status,200);assert.deepEqual(await r.json(),{ok:true,service:'lume',protocol:1});r=await handle(req('/v1/ready'),env(DB));assert.equal(r.status,200);const j=await r.json();assert.equal(j.ok,true);assert.equal(j.durable,true);assert.equal(j.revision,1)});
test('login issues signed session and rejects invalid password',async()=>{const DB=new D1Mock();await seed(DB);const h=await authHeader(DB,' ALUNO ','senha-aleatoria-aluno-123456');const token=h.authorization.slice(7);const verified=await verifySession(token,AUTH_SECRET);assert.equal(verified.profileId,'p1');assert.equal(verified.role,'consumer');const bad=await handle(req('/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'aluno',password:'errada'})}),env(DB));assert.equal(bad.status,401)});
test('login rate limiter produces retryable 429',async()=>{const DB=new D1Mock();await seed(DB);const e=env(DB);e.LOGIN_RATE_LIMITER={async limit(){return {success:false}}};const r=await handle(req('/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'aluno',password:'x'})}),e);assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'60')});
test('bootstrap requires auth, preserves integer revision and editorial fields',async()=>{const DB=new D1Mock();await seed(DB);let r=await handle(req('/v1/bootstrap?since=0'),env(DB));assert.equal(r.status,401);const h=await authHeader(DB,'aluno','senha-aleatoria-aluno-123456');r=await handle(req('/v1/bootstrap?since=0',{headers:h}),env(DB));assert.equal(r.status,200);const j=await r.json();assert.equal(j.revision,1);assert.deepEqual(j.works[0].sections,['Grandes Clássicos']);assert.deepEqual(j.works[0].tags,['drama']);assert.equal(j.works[0].editions[0].sourceFileId,'drive-file-1');r=await handle(req('/v1/bootstrap?since=1',{headers:h}),env(DB));assert.equal(r.status,304)});
test('current Flutter ops sync contract returns ack/events/rejected',async()=>{const DB=new D1Mock();await seed(DB);const h=await authHeader(DB,'aluno','senha-aleatoria-aluno-123456');const op={kind:'progress',profileId:'p1',editionId:'e1',opId:'op-1',locator:{kind:'page',page:3,pageCount:10},percent:.3,clientUpdatedAt:1760000000000,completed:false,deviceId:'android-1'};let r=await handle(req('/v1/profiles/p1/sync',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({cursor:'0',ops:[op,{kind:'favorite',opId:'bad-1'}]})}),env(DB));assert.equal(r.status,200);let j=await r.json();assert.deepEqual(j.ack,['op-1']);assert.equal(j.rejected[0].opId,'bad-1');assert.equal(j.events.length,1);assert.equal(j.events[0].profile,'p1');assert.equal(j.events[0].edition,'e1');assert.equal(typeof j.events[0].seq,'number');assert.equal(j.cursor,String(j.events[0].seq));const cursor=j.cursor;r=await handle(req('/v1/profiles/p1/sync',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({cursor,ops:[op]})}),env(DB));j=await r.json();assert.deepEqual(j.ack,['op-1']);assert.equal(j.events.length,0);assert.equal(j.cursor,cursor)});
test('legacy operations field remains accepted during migration',async()=>{const DB=new D1Mock();await seed(DB);const h=await authHeader(DB,'aluno','senha-aleatoria-aluno-123456');const op={type:'progress',editionId:'e1',opId:'legacy-1',locator:{kind:'page',page:1,pageCount:10},percent:.1,clientUpdatedAt:1760000000001,completed:false};const r=await handle(req('/v1/profiles/p1/sync',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({cursor:'0',operations:[op]})}),env(DB));const j=await r.json();assert.deepEqual(j.ack,['legacy-1']);assert.equal(j.events.length,1)});
test('consumer cannot cross profile; admin can',async()=>{const DB=new D1Mock();await seed(DB);const user=await authHeader(DB,'aluno','senha-aleatoria-aluno-123456');let r=await handle(req('/v1/profiles/pa/sync',{method:'POST',headers:{...user,'content-type':'application/json'},body:'{"cursor":"0","ops":[]}'}),env(DB));assert.equal(r.status,403);const admin=await authHeader(DB,'admin','senha-aleatoria-admin-123456');r=await handle(req('/v1/profiles/p1/sync',{method:'POST',headers:{...admin,'content-type':'application/json'},body:'{"cursor":"0","ops":[]}'}),env(DB));assert.equal(r.status,200)});
test('admin catalog route enforces role and updates catalog atomically',async()=>{const DB=new D1Mock();await seed(DB);const user=await authHeader(DB,'aluno','senha-aleatoria-aluno-123456'),admin=await authHeader(DB,'admin','senha-aleatoria-admin-123456');const manifest={revision:2,full:true,works:[{id:'w2',canonicalTitle:'PLUTO',displayTitle:'Pluto',type:'manga',sections:['Essenciais'],tags:['mystery'],editions:[{id:'e2',format:'pdf',sourceFileId:'f2',fileName:'Pluto.pdf',byteSize:500}]}],tombstones:[]};let r=await handle(req('/v1/admin/catalog',{method:'POST',headers:{...user,'content-type':'application/json'},body:JSON.stringify(manifest)}),env(DB));assert.equal(r.status,403);r=await handle(req('/v1/admin/catalog',{method:'POST',headers:{...admin,'content-type':'application/json'},body:JSON.stringify(manifest)}),env(DB));assert.equal(r.status,200);assert.equal((await r.json()).revision,2);const b=await new D1Store(DB).bootstrap(0);assert.equal(b.works.length,1);assert.equal(b.works[0].id,'w2');assert.deepEqual(b.works[0].sections,['Essenciais']);await assert.rejects(()=>applyCatalogManifest(DB,{...manifest,revision:1}),/catalog_revision_regression/);assert.equal(await new D1Store(DB).getRevision(),2)});
test('media descriptor is authenticated and returns Worker-signed URL required by Flutter',async()=>{const DB=new D1Mock();await seed(DB);let r=await handle(req('/v1/media/e1'),env(DB));assert.equal(r.status,401);const h=await authHeader(DB,'aluno','senha-aleatoria-aluno-123456');r=await handle(req('/v1/media/e1',{headers:h}),env(DB));assert.equal(r.status,200);const j=await r.json();assert.equal(j.editionId,'e1');assert.equal(j.byteSize,123);assert.equal(j.sha256,'abc');const u=new URL(j.url);assert.equal(u.pathname,'/v1/media/e1/file');assert.ok(u.searchParams.get('exp'));assert.ok(u.searchParams.get('sig'));const tampered=new URL(j.url);tampered.searchParams.set('sig','broken');r=await handle(new Request(tampered),env(DB));assert.equal(r.status,403);r=await handle(new Request(j.url),env(DB));assert.equal(r.status,502);assert.equal((await r.json()).error,'drive_auth_failed')});
test('Drive proxy preserves byte-range semantics without buffering',async()=>{let seen=null;const fetcher=async(url,init)=>{seen={url,init};return new Response('bytes',{status:206,headers:{'content-type':'application/pdf','content-range':'bytes 10-14/100','content-length':'5','accept-ranges':'bytes','etag':'"rev1"'}})};const r=await proxyDriveMedia(new Request('https://lume.example/file',{headers:{range:'bytes=10-','if-range':'"rev1"'}}),{},'drive-file',{fetcher,tokenProvider:async()=> 'token'});assert.equal(r.status,206);assert.equal(await r.text(),'bytes');assert.equal(r.headers.get('content-range'),'bytes 10-14/100');assert.equal(seen.init.headers.range,'bytes=10-');assert.equal(seen.init.headers['if-range'],'"rev1"');assert.match(seen.url,/drive\/v3\/files\/drive-file/)});
